### PR TITLE
chore(docs): update homebrew installation note

### PR DESCRIPTION
**Pull request by chenrui333**
update the installation note per https://github.com/Homebrew/homebrew-core/pull/200767 merge :) 

formula page, https://formulae.brew.sh/formula/macmon

### CODE REVIEW

**Comment by vladkens** [comment]
@chenrui333

Thank you for doing that!

**Comment by i0ntempest** [comment]
macmon is now on MacPorts as well, do you want that in the doc too?

**Comment by vladkens** [comment]
@i0ntempest hi, that would be great. Can you make a PR?

**Comment by i0ntempest** [comment]
> @i0ntempest hi, that would be great. Can you make a PR?

Yup, will do when I get to my computer

**Pull request merged**
